export const translations = {
  es: {
    // Navegación
    nav: {
      dashboard: 'Panel Principal',
      students: 'Estudiantes',
      subjects: 'Materias',
      enrollments: 'Inscripciones',
      gradeManagement: 'Gestión de Notas',
      calendar: 'Calendario',
      reports: 'Reportes',
      users: 'Usuarios',
      academicPeriods: 'Períodos Académicos',
      studentHistory: 'Historial de Estudiantes',
      settings: 'Configuración',
      logout: 'Cerrar Sesión'
    },
    // Común
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      add: 'Agregar',
      search: 'Buscar',
      filter: 'Filtrar',
      export: 'Exportar',
      import: 'Importar',
      close: 'Cerrar',
      confirm: 'Confirmar',
      yes: 'Sí',
      no: 'No',
      loading: 'Cargando...',
      noData: 'No hay datos disponibles',
      error: 'Error',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Información'
    },
    // Dashboard
    dashboard: {
      welcome: 'Bienvenido',
      totalStudents: 'Total de Estudiantes',
      totalSubjects: 'Total de Materias',
      activeEnrollments: 'Inscripciones Activas',
      averageGrade: 'Promedio General'
    },
    // Estudiantes
    students: {
      title: 'Estudiantes',
      subtitle: 'Gestiona el registro de estudiantes',
      newStudent: 'Nuevo Estudiante',
      name: 'Nombre',
      matricula: 'Matrícula',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      address: 'Dirección',
      status: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo'
    },
    // Materias
    subjects: {
      title: 'Materias',
      subtitle: 'Gestiona el currículo académico',
      newSubject: 'Nueva Materia',
      name: 'Nombre de la Materia',
      code: 'Código',
      codeAutoGenerated: 'Código (Auto-generado)',
      teacher: 'Docente',
      credits: 'Créditos',
      schedule: 'Horario',
      academicPeriod: 'Período Académico',
      selectPeriod: '-- Seleccionar Período --',
      evaluationConfig: 'Configuración de Evaluación'
    },
    // Configuración
    settings: {
      title: 'Configuración',
      theme: 'Tema',
      lightMode: 'Modo Claro',
      darkMode: 'Modo Oscuro',
      language: 'Idioma',
      colorPreview: 'Vista Previa de Colores',
      primary: 'Principal',
      secondary: 'Secundario',
      success: 'Éxito',
      warning: 'Advertencia',
      danger: 'Peligro'
    },
    // Períodos Académicos
    periods: {
      title: 'Períodos Académicos',
      subtitle: 'Gestiona los cuatrimestres y el registro histórico',
      newPeriod: 'Nuevo Período',
      totalPeriods: 'Total de Períodos',
      activePeriod: 'Período Activo',
      activeStudents: 'Estudiantes Activos',
      historicalTotal: 'Total Histórico',
      viewDetails: 'Ver Detalles',
      activate: 'Activar',
      active: 'Activo',
      year: 'Año',
      quarter: 'Cuatrimestre'
    },
    // Calificaciones
    grades: {
      title: 'Calificaciones',
      subtitle: 'Gestión y registro de notas académicas',
      selectSubject: 'Seleccionar Materia',
      selectPeriod: 'Seleccionar Período',
      studentName: 'Estudiante',
      partial1: 'P1',
      partial2: 'P2',
      partial3: 'P3',
      partial4: 'P4',
      exam: 'Examen',
      final: 'Final',
      comments: 'Comentarios',
      updateSuccess: 'Notas actualizadas correctamente',
      average: 'Promedio'
    },
    // Calendario
    calendar: {
      title: 'Calendario Académico',
      subtitle: 'Eventos importantes y fechas límite',
      newEvent: 'Nuevo Evento',
      eventTitle: 'Título del evento',
      eventDate: 'Fecha',
      eventDescription: 'Descripción',
      type: 'Tipo',
      exam: 'Examen',
      holiday: 'Feriado',
      activity: 'Actividad',
      meeting: 'Reunión'
    },
    // Reportes
    reports: {
      title: 'Reportes',
      subtitle: 'Generación de documentos y estadísticas',
      generatePDF: 'Generar PDF',
      sendWhatsApp: 'Enviar por WhatsApp',
      download: 'Descargar',
      selectStudent: 'Seleccionar Estudiante',
      academicRecord: 'Récord de Notas',
      certificate: 'Certificado de Estudios'
    }
  },
  en: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      students: 'Students',
      subjects: 'Subjects',
      enrollments: 'Enrollments',
      gradeManagement: 'Grade Management',
      calendar: 'Calendar',
      reports: 'Reports',
      users: 'Users',
      academicPeriods: 'Academic Periods',
      studentHistory: 'Student History',
      settings: 'Settings',
      logout: 'Logout'
    },
    // Common
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      export: 'Export',
      import: 'Import',
      close: 'Close',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      loading: 'Loading...',
      noData: 'No data available',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Information'
    },
    // Dashboard
    dashboard: {
      welcome: 'Welcome',
      totalStudents: 'Total Students',
      totalSubjects: 'Total Subjects',
      activeEnrollments: 'Active Enrollments',
      averageGrade: 'Average Grade'
    },
    // Students
    students: {
      title: 'Students',
      subtitle: 'Manage student records',
      newStudent: 'New Student',
      name: 'Name',
      matricula: 'ID Number',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive'
    },
    // Subjects
    subjects: {
      title: 'Subjects',
      subtitle: 'Manage academic curriculum',
      newSubject: 'New Subject',
      name: 'Subject Name',
      code: 'Code',
      codeAutoGenerated: 'Code (Auto-generated)',
      teacher: 'Teacher',
      credits: 'Credits',
      schedule: 'Schedule',
      academicPeriod: 'Academic Period',
      selectPeriod: '-- Select Period --',
      evaluationConfig: 'Evaluation Configuration'
    },
    // Settings
    settings: {
      title: 'Settings',
      theme: 'Theme',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      language: 'Language',
      colorPreview: 'Color Preview',
      primary: 'Primary',
      secondary: 'Secondary',
      success: 'Success',
      warning: 'Warning',
      danger: 'Danger'
    },
    // Academic Periods
    periods: {
      title: 'Academic Periods',
      subtitle: 'Manage quarters and historical records',
      newPeriod: 'New Period',
      totalPeriods: 'Total Periods',
      activePeriod: 'Active Period',
      activeStudents: 'Active Students',
      historicalTotal: 'Historical Total',
      viewDetails: 'View Details',
      activate: 'Activate',
      active: 'Active',
      year: 'Year',
      quarter: 'Quarter'
    },
    // Grades
    grades: {
      title: 'Grades',
      subtitle: 'Manage and record academic scores',
      selectSubject: 'Select Subject',
      selectPeriod: 'Select Period',
      studentName: 'Student',
      partial1: 'Q1',
      partial2: 'Q2',
      partial3: 'Q3',
      partial4: 'Q4',
      exam: 'Exam',
      final: 'Final',
      comments: 'Comments',
      updateSuccess: 'Grades updated successfully',
      average: 'Average'
    },
    // Calendar
    calendar: {
      title: 'Academic Calendar',
      subtitle: 'Important events and deadlines',
      newEvent: 'New Event',
      eventTitle: 'Event Title',
      eventDate: 'Date',
      eventDescription: 'Description',
      type: 'Type',
      exam: 'Exam',
      holiday: 'Holiday',
      activity: 'Activity',
      meeting: 'Meeting'
    },
    // Reports
    reports: {
      title: 'Reports',
      subtitle: 'Generate documents and statistics',
      generatePDF: 'Generate PDF',
      sendWhatsApp: 'Send via WhatsApp',
      download: 'Download',
      selectStudent: 'Select Student',
      academicRecord: 'Academic Record',
      certificate: 'Study Certificate'
    }
  },
  ht: {
    // Navigasyon
    nav: {
      dashboard: 'Tablo Bò',
      students: 'Elèv yo',
      subjects: 'Matye yo',
      enrollments: 'Enskripsyon',
      gradeManagement: 'Jesyon Nòt',
      calendar: 'Kalandriye',
      reports: 'Rapò',
      users: 'Itilizatè',
      academicPeriods: 'Peryòd Akademik',
      studentHistory: 'Istwa Elèv',
      settings: 'Paramèt',
      logout: 'Dekonekte'
    },
    // Komen
    common: {
      save: 'Anrejistre',
      cancel: 'Anile',
      delete: 'Efase',
      edit: 'Modifye',
      add: 'Ajoute',
      search: 'Chèche',
      filter: 'Filtre',
      export: 'Ekspòte',
      import: 'Enpòte',
      close: 'Fèmen',
      confirm: 'Konfime',
      yes: 'Wi',
      no: 'Non',
      loading: 'Chajman...',
      noData: 'Pa gen done disponib',
      error: 'Erè',
      success: 'Siksè',
      warning: 'Avètisman',
      info: 'Enfòmasyon'
    },
    // Tablo Bò
    dashboard: {
      welcome: 'Byenveni',
      totalStudents: 'Total Elèv',
      totalSubjects: 'Total Matye',
      activeEnrollments: 'Enskripsyon Aktif',
      averageGrade: 'Mwayèn Jeneral'
    },
    // Elèv yo
    students: {
      title: 'Elèv yo',
      subtitle: 'Jere dosye elèv yo',
      newStudent: 'Nouvo Elèv',
      name: 'Non',
      matricula: 'Nimewo Idantifikasyon',
      email: 'Imèl',
      phone: 'Telefòn',
      address: 'Adrès',
      status: 'Estati',
      active: 'Aktif',
      inactive: 'Inaktif'
    },
    // Matye yo
    subjects: {
      title: 'Matye yo',
      subtitle: 'Jere pwogram akademik',
      newSubject: 'Nouvo Matye',
      name: 'Non Matye',
      code: 'Kòd',
      codeAutoGenerated: 'Kòd (Otomatik)',
      teacher: 'Pwofesè',
      credits: 'Kredi',
      schedule: 'Orè',
      academicPeriod: 'Peryòd Akademik',
      selectPeriod: '-- Chwazi Peryòd --',
      evaluationConfig: 'Konfigirasyon Evalyasyon'
    },
    // Paramèt
    settings: {
      title: 'Paramèt',
      theme: 'Tèm',
      lightMode: 'Mòd Klè',
      darkMode: 'Mòd Fènwa',
      language: 'Lang',
      colorPreview: 'Apèsi Koulè',
      primary: 'Prensipal',
      secondary: 'Segondè',
      success: 'Siksè',
      warning: 'Avètisman',
      danger: 'Danje'
    },
    // Peryòd Akademik
    periods: {
      title: 'Peryòd Akademik',
      subtitle: 'Jere trimès ak dosye istorik',
      newPeriod: 'Nouvo Peryòd',
      totalPeriods: 'Total Peryòd',
      activePeriod: 'Peryòd Aktif',
      activeStudents: 'Elèv Aktif',
      historicalTotal: 'Total Istorik',
      viewDetails: 'Wè Detay',
      activate: 'Aktive',
      active: 'Aktif',
      year: 'Ane',
      quarter: 'Trimès'
    },
    // Nòt
    grades: {
      title: 'Nòt',
      subtitle: 'Jesyon ak anrejistreman nòt akademik',
      selectSubject: 'Chwazi Matye',
      selectPeriod: 'Chwazi Peryòd',
      studentName: 'Elèv',
      partial1: 'P1',
      partial2: 'P2',
      partial3: 'P3',
      partial4: 'P4',
      exam: 'Egzamen',
      final: 'Final',
      comments: 'Kòmantè',
      updateSuccess: 'Nòt yo mete ajou avèk siksè',
      average: 'Mwayèn'
    },
    // Kalandriye
    calendar: {
      title: 'Kalandriye Akademik',
      subtitle: 'Evènman enpòtan ak dat limit yo',
      newEvent: 'Nouvo Evènman',
      eventTitle: 'Tit evènman an',
      eventDate: 'Dat',
      eventDescription: 'Deskripsyon',
      type: 'Kalite',
      exam: 'Egzamen',
      holiday: 'Jou Ferye',
      activity: 'Aktivite',
      meeting: 'Reyinyon'
    },
    // Rapò
    reports: {
      title: 'Rapò',
      subtitle: 'Jenerasyon dokiman ak estatistik',
      generatePDF: 'Jenere PDF',
      sendWhatsApp: 'Voye sou WhatsApp',
      download: 'Telechaje',
      selectStudent: 'Chwazi Elèv',
      academicRecord: 'Dosye Nòt',
      certificate: 'Sètifika Etid'
    }
  }
};

export const languageNames = {
  es: 'Español',
  en: 'English',
  ht: 'Kreyòl'
};

export const languageFlags = {
  es: '🇪🇸',
  en: '🇺🇸',
  ht: '🇭🇹'
};
