export const translations = {
  es: {
    // Navegación
    nav: {
      dashboard: 'Panel Principal',
      students: 'Estudiantes',
      subjects: 'Materias',
      enrollments: 'Inscripciones',
      gradeManagement: 'Gestión de Notas',
      calendar: 'Calendario',
      reports: 'Reportes',
      users: 'Usuarios',
      academicPeriods: 'Períodos Académicos',
      studentHistory: 'Historial de Estudiantes',
      attendance: 'Control de Asistencia',
      analytics: 'Analítica Avanzada',
      about: 'Acerca de',
      settings: 'Configuración',
      logout: 'Cerrar Sesión'
    },
    // Común
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      add: 'Agregar',
      search: 'Buscar',
      filter: 'Filtrar',
      export: 'Exportar',
      import: 'Importar',
      close: 'Cerrar',
      confirm: 'Confirmar',
      yes: 'Sí',
      no: 'No',
      loading: 'Cargando...',
      noData: 'No hay datos disponibles',
      error: 'Error',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Información'
    },
    // Dashboard
    dashboard: {
      welcome: 'Bienvenido',
      totalStudents: 'Total de Estudiantes',
      totalSubjects: 'Total de Materias',
      activeEnrollments: 'Inscripciones Activas',
      averageGrade: 'Promedio General'
    },
    // Estudiantes
    students: {
      title: 'Estudiantes',
      subtitle: 'Gestiona el registro de estudiantes',
      newStudent: 'Nuevo Estudiante',
      name: 'Nombre',
      matricula: 'Matrícula',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      address: 'Dirección',
      status: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo'
    },
    // Materias
    subjects: {
      title: 'Materias',
      subtitle: 'Gestiona el currículo académico',
      newSubject: 'Nueva Materia',
      name: 'Nombre de la Materia',
      code: 'Código',
      codeAutoGenerated: 'Código (Auto-generado)',
      teacher: 'Docente',
      credits: 'Créditos',
      schedule: 'Horario',
      academicPeriod: 'Período Académico',
      selectPeriod: '-- Seleccionar Período --',
      evaluationConfig: 'Configuración de Evaluación'
    },
    // Configuración
    settings: {
      title: 'Configuración',
      theme: 'Tema',
      lightMode: 'Modo Claro',
      darkMode: 'Modo Oscuro',
      language: 'Idioma 🇩🇴',
      colorPreview: 'Vista Previa de Colores',
      primary: 'Principal',
      secondary: 'Secundario',
      success: 'Éxito',
      warning: 'Advertencia',
      danger: 'Peligro'
    },
    // Períodos Académicos
    periods: {
      title: 'Períodos Académicos',
      subtitle: 'Gestiona los cuatrimestres y el registro histórico',
      newPeriod: 'Nuevo Período',
      totalPeriods: 'Total de Períodos',
      activePeriod: 'Período Activo',
      activeStudents: 'Estudiantes Activos',
      historicalTotal: 'Total Histórico',
      viewDetails: 'Ver Detalles',
      activate: 'Activar',
      active: 'Activo',
      year: 'Año',
      quarter: 'Cuatrimestre'
    },
    // Asistencia
    attendance: {
      title: 'Control de Asistencia',
      subtitle: 'Gestiona la presencia diaria de los estudiantes',
      date: 'Fecha de Asistencia',
      present: 'Presente',
      absent: 'Ausento',
      late: 'Tardanza',
      excused: 'Justificado',
      saveAttendance: 'Guardar Asistencia',
      markAllPresent: 'Marcar todos como Presente',
      stats: 'Estadísticas de Asistencia',
      selectSubject: 'Seleccionar Materia para pasar lista'
    },
    // Analítica
    analytics: {
      title: 'Panel de Analítica',
      subtitle: 'Visualización de datos y rendimiento académico',
      gradeDistribution: 'Distribución de Calificaciones',
      subjectPerformance: 'Rendimiento por Materia',
      attendanceOverview: 'Resumen de Asistencia Global',
      averageGrade: 'Promedio General',
      totalStudents: 'Total Estudiantes'
    },
    // Acerca de
    about: {
      title: 'Acerca de GradePro',
      creator: 'Creado por',
      developer: 'Dauris Santana',
      exclusivity: 'Software desarrollado exclusivamente para el uso de "Global Effect"',
      legalTitle: 'Aviso Legal y Propiedad Intelectual',
      legalText: 'Este software está protegido por la Ley No. 65-00 sobre Derecho de Autor de la República Dominicana y tratados internacionales asociados. La reproducción, distribución, plagio o cualquier uso no autorizado de este programa constituye una violación legal sujeta a severas sanciones civiles y penales conforme a la legislación dominicana. El código fuente y su arquitectura son propiedad intelectual exclusiva del autor, prohibiéndose terminantemente su modificación o ingeniería inversa sin autorización expresa.',
      version: 'Versión 1.1.2'
    },
    // Calificaciones
    grades: {
      title: 'Calificaciones',
      subtitle: 'Gestión y registro de notas académicas',
      selectSubject: 'Seleccionar Materia',
      selectPeriod: 'Seleccionar Período',
      studentName: 'Estudiante',
      partial1: 'P1',
      partial2: 'P2',
      partial3: 'P3',
      partial4: 'P4',
      exam: 'Examen',
      final: 'Final',
      comments: 'Comentarios',
      updateSuccess: 'Notas actualizadas correctamente',
      average: 'Promedio'
    },
    // Calendario
    calendar: {
      title: 'Calendario Académico',
      subtitle: 'Eventos importantes y fechas límite',
      newEvent: 'Nuevo Evento',
      eventTitle: 'Título del evento',
      eventDate: 'Fecha',
      eventDescription: 'Descripción',
      type: 'Tipo',
      exam: 'Examen',
      holiday: 'Feriado',
      activity: 'Actividad',
      meeting: 'Reunión'
    },
    // Reportes
    reports: {
      title: 'Reportes',
      subtitle: 'Generación de documentos y estadísticas',
      generatePDF: 'Generar PDF',
      sendWhatsApp: 'Enviar por WhatsApp',
      download: 'Descargar',
      selectStudent: 'Seleccionar Estudiante',
      academicRecord: 'Récord de Notas',
      certificate: 'Certificado de Estudios'
    }
  },
  en: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      students: 'Students',
      subjects: 'Subjects',
      enrollments: 'Enrollments',
      gradeManagement: 'Grade Management',
      calendar: 'Calendar',
      reports: 'Reports',
      users: 'Users',
      academicPeriods: 'Academic Periods',
      studentHistory: 'Student History',
      attendance: 'Attendance Control',
      analytics: 'Advanced Analytics',
      about: 'About',
      settings: 'Settings',
      logout: 'Logout'
    },
    // Common
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      filter: 'Filter',
      export: 'Export',
      import: 'Import',
      close: 'Close',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      loading: 'Loading...',
      noData: 'No data available',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Information'
    },
    // Dashboard
    dashboard: {
      welcome: 'Welcome',
      totalStudents: 'Total Students',
      totalSubjects: 'Total Subjects',
      activeEnrollments: 'Active Enrollments',
      averageGrade: 'Average Grade'
    },
    // Students
    students: {
      title: 'Students',
      subtitle: 'Manage student records',
      newStudent: 'New Student',
      name: 'Name',
      matricula: 'ID Number',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive'
    },
    // Subjects
    subjects: {
      title: 'Subjects',
      subtitle: 'Manage academic curriculum',
      newSubject: 'New Subject',
      name: 'Subject Name',
      code: 'Code',
      codeAutoGenerated: 'Code (Auto-generated)',
      teacher: 'Teacher',
      credits: 'Credits',
      schedule: 'Schedule',
      academicPeriod: 'Academic Period',
      selectPeriod: '-- Select Period --',
      evaluationConfig: 'Evaluation Configuration'
    },
    // Settings
    settings: {
      title: 'Settings',
      theme: 'Theme',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      language: 'Language 🇺🇸',
      colorPreview: 'Color Preview',
      primary: 'Primary',
      secondary: 'Secondary',
      success: 'Success',
      warning: 'Warning',
      danger: 'Danger'
    },
    // Academic Periods
    periods: {
      title: 'Academic Periods',
      subtitle: 'Manage quarters and historical records',
      newPeriod: 'New Period',
      totalPeriods: 'Total Periods',
      activePeriod: 'Active Period',
      activeStudents: 'Active Students',
      historicalTotal: 'Historical Total',
      viewDetails: 'View Details',
      activate: 'Activate',
      active: 'Active',
      year: 'Year',
      quarter: 'Quarter'
    },
    // Attendance
    attendance: {
      title: 'Attendance Control',
      subtitle: 'Manage daily student presence',
      date: 'Attendance Date',
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      excused: 'Excused',
      saveAttendance: 'Save Attendance',
      markAllPresent: 'Mark all as Present',
      stats: 'Attendance Stats',
      selectSubject: 'Select Subject to take attendance'
    },
    // Analytics
    analytics: {
      title: 'Analytics Dashboard',
      subtitle: 'Data visualization and academic performance',
      gradeDistribution: 'Grade Distribution',
      subjectPerformance: 'Subject Performance',
      attendanceOverview: 'Global Attendance Overview',
      averageGrade: 'General Average',
      totalStudents: 'Total Students'
    },
    // About
    about: {
      title: 'About GradePro',
      creator: 'Created by',
      developer: 'Dauris Santana',
      exclusivity: 'Software developed exclusively for the use of "Global Effect"',
      legalTitle: 'Legal Notice and Intellectual Property',
      legalText: 'This software is protected by Law No. 65-00 on Copyright of the Dominican Republic and international intellectual property treaties. Unauthorized reproduction, distribution, plagiarism, or any use of this program constitutes a legal violation subject to severe civil and criminal penalties under Dominican legislation. The source code and its architecture are the exclusive intellectual property of the author, and any modification or reverse engineering without express consent is strictly prohibited.',
      version: 'Version 1.1.2'
    },
    // Grades
    grades: {
      title: 'Grades',
      subtitle: 'Manage and record academic scores',
      selectSubject: 'Select Subject',
      selectPeriod: 'Select Period',
      studentName: 'Student',
      partial1: 'Q1',
      partial2: 'Q2',
      partial3: 'Q3',
      partial4: 'Q4',
      exam: 'Exam',
      final: 'Final',
      comments: 'Comments',
      updateSuccess: 'Grades updated successfully',
      average: 'Average'
    },
    // Calendar
    calendar: {
      title: 'Academic Calendar',
      subtitle: 'Important events and deadlines',
      newEvent: 'New Event',
      eventTitle: 'Event Title',
      eventDate: 'Date',
      eventDescription: 'Description',
      type: 'Type',
      exam: 'Exam',
      holiday: 'Holiday',
      activity: 'Activity',
      meeting: 'Meeting'
    },
    // Reports
    reports: {
      title: 'Reports',
      subtitle: 'Generate documents and statistics',
      generatePDF: 'Generate PDF',
      sendWhatsApp: 'Send via WhatsApp',
      download: 'Download',
      selectStudent: 'Select Student',
      academicRecord: 'Academic Record',
      certificate: 'Study Certificate'
    }
  },
  ht: {
    // Navigasyon
    nav: {
      dashboard: 'Tablo Bò',
      students: 'Elèv yo',
      subjects: 'Matye yo',
      enrollments: 'Enskripsyon',
      gradeManagement: 'Jesyon Nòt',
      calendar: 'Kalandriye',
      reports: 'Rapò',
      users: 'Itilizatè',
      academicPeriods: 'Peryòd Akademik',
      studentHistory: 'Istwa Elèv',
      attendance: 'Kontwòl Prezan',
      settings: 'Paramèt',
      logout: 'Dekonekte'
    },
    // Komen
    common: {
      save: 'Anrejistre',
      cancel: 'Anile',
      delete: 'Efase',
      edit: 'Modifye',
      add: 'Ajoute',
      search: 'Chèche',
      filter: 'Filtre',
      export: 'Ekspòte',
      import: 'Enpòte',
      close: 'Fèmen',
      confirm: 'Konfime',
      yes: 'Wi',
      no: 'Non',
      loading: 'Chajman...',
      noData: 'Pa gen done disponib',
      error: 'Erè',
      success: 'Siksè',
      warning: 'Avètisman',
      info: 'Enfòmasyon'
    },
    // Tablo Bò
    dashboard: {
      welcome: 'Byenveni',
      totalStudents: 'Total Elèv',
      totalSubjects: 'Total Matye',
      activeEnrollments: 'Enskripsyon Aktif',
      averageGrade: 'Mwayèn Jeneral'
    },
    // Elèv yo
    students: {
      title: 'Elèv yo',
      subtitle: 'Jere dosye elèv yo',
      newStudent: 'Nouvo Elèv',
      name: 'Non',
      matricula: 'Nimewo Idantifikasyon',
      email: 'Imèl',
      phone: 'Telefòn',
      address: 'Adrès',
      status: 'Estati',
      active: 'Aktif',
      inactive: 'Inaktif'
    },
    // Matye yo
    subjects: {
      title: 'Matye yo',
      subtitle: 'Jere pwogram akademik',
      newSubject: 'Nouvo Matye',
      name: 'Non Matye',
      code: 'Kòd',
      codeAutoGenerated: 'Kòd (Otomatik)',
      teacher: 'Pwofesè',
      credits: 'Kredi',
      schedule: 'Orè',
      academicPeriod: 'Peryòd Akademik',
      selectPeriod: '-- Chwazi Peryòd --',
      evaluationConfig: 'Konfigirasyon Evalyasyon'
    },
    // Paramèt
    settings: {
      title: 'Paramèt',
      theme: 'Tèm',
      lightMode: 'Mòd Klè',
      darkMode: 'Mòd Fènwa',
      language: 'Lang 🇭🇹',
      colorPreview: 'Apèsi Koulè',
      primary: 'Prensipal',
      secondary: 'Segondè',
      success: 'Siksè',
      warning: 'Avètisman',
      danger: 'Danje'
    },
    // Peryòd Akademik
    periods: {
      title: 'Peryòd Akademik',
      subtitle: 'Jere trimès ak dosye istorik',
      newPeriod: 'Nouvo Peryòd',
      totalPeriods: 'Total Peryòd',
      activePeriod: 'Peryòd Aktif',
      activeStudents: 'Elèv Aktif',
      historicalTotal: 'Total Istorik',
      viewDetails: 'Wè Detay',
      activate: 'Aktive',
      active: 'Aktif',
      year: 'Ane',
      quarter: 'Trimès'
    },
    // Attendance
    attendance: {
      title: 'Kontwòl Prezan',
      subtitle: 'Jere prezans elèv yo chak jou',
      date: 'Dat Prezans',
      present: 'Prezan',
      absent: 'Absan',
      late: 'An reta',
      excused: 'Eskize',
      saveAttendance: 'Anrejistre Prezans',
      markAllPresent: 'Make tout moun Prezan',
      stats: 'Estatistik Prezans',
      selectSubject: 'Chwazi Matye pou fè apèl'
    },
    // Nòt
    grades: {
      title: 'Nòt',
      subtitle: 'Jesyon ak anrejistreman nòt akademik',
      selectSubject: 'Chwazi Matye',
      selectPeriod: 'Chwazi Peryòd',
      studentName: 'Elèv',
      partial1: 'P1',
      partial2: 'P2',
      partial3: 'P3',
      partial4: 'P4',
      exam: 'Egzamen',
      final: 'Final',
      comments: 'Kòmantè',
      updateSuccess: 'Nòt yo mete ajou avèk siksè',
      average: 'Mwayèn'
    },
    // Kalandriye
    calendar: {
      title: 'Kalandriye Akademik',
      subtitle: 'Evènman enpòtan ak dat limit yo',
      newEvent: 'Nouvo Evènman',
      eventTitle: 'Tit evènman an',
      eventDate: 'Dat',
      eventDescription: 'Deskripsyon',
      type: 'Kalite',
      exam: 'Egzamen',
      holiday: 'Jou Ferye',
      activity: 'Aktivite',
      meeting: 'Reyinyon'
    },
    // Rapò
    reports: {
      title: 'Rapò',
      subtitle: 'Jenerasyon dokiman ak estatistik',
      generatePDF: 'Jenere PDF',
      sendWhatsApp: 'Voye sou WhatsApp',
      download: 'Telechaje',
      selectStudent: 'Chwazi Elèv',
      academicRecord: 'Dosye Nòt',
      certificate: 'Sètifika Etid'
    }
  },
  fr: {
    // Navigation
    nav: {
      dashboard: 'Tableau de bord',
      students: 'Étudiants',
      subjects: 'Matieres',
      enrollments: 'Inscriptions',
      gradeManagement: 'Gestion des Notes',
      calendar: 'Calendrier',
      reports: 'Rapports',
      users: 'Utilisateurs',
      academicPeriods: 'Périodes Académiques',
      studentHistory: 'Historique Étudiant',
      attendance: 'Contrôle d\'Assiduité',
      settings: 'Paramètres',
      logout: 'Déconnexion'
    },
    // Commun
    common: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      add: 'Ajouter',
      search: 'Rechercher',
      filter: 'Filtrer',
      export: 'Exporter',
      import: 'Importer',
      close: 'Fermer',
      confirm: 'Confirmer',
      yes: 'Oui',
      no: 'Non',
      loading: 'Chargement...',
      noData: 'Aucune donnée disponible',
      error: 'Erreur',
      success: 'Succès',
      warning: 'Avertissement',
      info: 'Information'
    },
    // Tableau de bord
    dashboard: {
      welcome: 'Bienvenue',
      totalStudents: 'Total Étudiants',
      totalSubjects: 'Total Matières',
      activeEnrollments: 'Inscriptions Actives',
      averageGrade: 'Moyenne Générale'
    },
    // Étudiants
    students: {
      title: 'Étudiants',
      subtitle: 'Gérer les dossiers des étudiants',
      newStudent: 'Nouvel Étudiant',
      name: 'Nom',
      matricula: 'Matricule',
      email: 'Email',
      phone: 'Téléphone',
      address: 'Adresse',
      status: 'Statut',
      active: 'Actif',
      inactive: 'Inactif'
    },
    // Matières
    subjects: {
      title: 'Matières',
      subtitle: 'Gérer le programme académique',
      newSubject: 'Nouvelle Matière',
      name: 'Nom de la Matière',
      code: 'Code',
      codeAutoGenerated: 'Code (Auto-généré)',
      teacher: 'Enseignant',
      credits: 'Crédits',
      schedule: 'Horaire',
      academicPeriod: 'Période Académique',
      selectPeriod: '-- Sélectionner Période --',
      evaluationConfig: 'Configuration de l\'évaluation'
    },
    // Paramètres
    settings: {
      title: 'Paramètres',
      theme: 'Thème',
      lightMode: 'Mode Clair',
      darkMode: 'Mode Sombre',
      language: 'Langue 🇫🇷',
      colorPreview: 'Aperçu des Couleurs',
      primary: 'Primaire',
      secondary: 'Secondaire',
      success: 'Succès',
      warning: 'Avertissement',
      danger: 'Danger'
    },
    // Périodes Académiques
    periods: {
      title: 'Périodes Académiques',
      subtitle: 'Gérer les trimestres et les dossiers historiques',
      newPeriod: 'Nouvelle Période',
      totalPeriods: 'Total Périodes',
      activePeriod: 'Période Active',
      activeStudents: 'Étudiants Actifs',
      historicalTotal: 'Total Historique',
      viewDetails: 'Voir Détails',
      activate: 'Activer',
      active: 'Actif',
      year: 'Année',
      quarter: 'Trimestre'
    },
    // Attendance
    attendance: {
      title: 'Contrôle d\'Assiduité',
      subtitle: 'Gérer la présence quotidienne des étudiants',
      date: 'Date de Présence',
      present: 'Présent',
      absent: 'Absent',
      late: 'Retard',
      excused: 'Justifié',
      saveAttendance: 'Enregistrer la Présence',
      markAllPresent: 'Marquer tous comme Présent',
      stats: 'Statisques de Présence',
      selectSubject: 'Sélectionner une Matière pour faire l\'appel'
    },
    // Notes
    grades: {
      title: 'Notes',
      subtitle: 'Gestion et enregistrement des notes académiques',
      selectSubject: 'Sélectionner Matière',
      selectPeriod: 'Sélectionner Période',
      studentName: 'Étudiant',
      partial1: 'P1',
      partial2: 'P2',
      partial3: 'P3',
      partial4: 'P4',
      exam: 'Examen',
      final: 'Final',
      comments: 'Commentaires',
      updateSuccess: 'Notes mises à jour avec succès',
      average: 'Moyenne'
    },
    // Calendrier
    calendar: {
      title: 'Calendrier Académique',
      subtitle: 'Événements importants et dates limites',
      newEvent: 'Nouvel Événement',
      eventTitle: 'Titre de l\'événement',
      eventDate: 'Date',
      eventDescription: 'Description',
      type: 'Type',
      exam: 'Examen',
      holiday: 'Vacances',
      activity: 'Activité',
      meeting: 'Réunion'
    },
    // Rapports
    reports: {
      title: 'Rapports',
      subtitle: 'Génération de documents et statistiques',
      generatePDF: 'Générer PDF',
      sendWhatsApp: 'Envoyer via WhatsApp',
      download: 'Télécharger',
      selectStudent: 'Sélectionner Étudiant',
      academicRecord: 'Relevé de Notes',
      certificate: 'Certificat d\'Études'
    }
  }
};

export const languageNames = {
  es: 'Español',
  en: 'English',
  fr: 'Français',
  ht: 'Kreyòl'
};

export const languageFlags = {
  es: '🇩🇴',
  en: '🇺🇸',
  fr: '🇫🇷',
  ht: '🇭🇹'
};
