// Servicio de envío de emails con plantilla profesional
// Incluye configuración de correo institucional y plantilla HTML

export const EmailService = {
    // Configuración del correo institucional
    config: {
        fromEmail: 'noreply@gradeapp.com', // Cambiar por tu correo institucional
        fromName: 'GradeApp - Sistema Académico',
        replyTo: 'soporte@gradeapp.com', // Cambiar por tu correo de soporte
    },

    // Generar plantilla HTML profesional (Multilenguaje)
    generateEmailTemplate: (student, reportType = 'individual', lang = 'es') => {
        const currentDate = new Date().toLocaleDateString(lang === 'en' ? 'en-US' : lang === 'fr' ? 'fr-FR' : 'es-ES', {
            weekday: 'long', 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric'
        });

        // Textos localizados básicos para el email
        const texts = {
            es: {
                title: 'Reporte Académico',
                systemName: 'Sistema de Gestión Académica',
                greeting: '¡Hola,',
                intro: 'Nos complace compartir contigo tu <strong>reporte académico actualizado</strong>. Adjunto a este correo encontrarás un documento PDF con el detalle completo de tus calificaciones.',
                includesTitle: '📊 Tu reporte incluye:',
                includes: [
                    'Calificaciones detalladas por materia',
                    'Promedio de asignaciones y exámenes',
                    'Calificación acumulada actualizada',
                    'Estado de aprobación de cada materia'
                ],
                motivationTitle: '💡 Recuerda:',
                motivation: 'Tu esfuerzo y dedicación son la clave del éxito. Sigue trabajando con constancia y verás los resultados. ¡Estamos aquí para apoyarte!',
                contact: 'Si tienes alguna pregunta sobre tus calificaciones o necesitas aclaraciones, no dudes en contactarnos. Estamos para ayudarte.',
                regards: 'Saludos cordiales,',
                legal: 'Este es un correo automático generado por GradeApp. Por favor, no respondas a este mensaje.'
            },
            en: {
                title: 'Academic Report',
                systemName: 'Academic Management System',
                greeting: 'Hello,',
                intro: 'We are pleased to share with you your <strong>updated academic report</strong>. Attached to this email you will find a PDF document with the full detail of your grades.',
                includesTitle: '📊 Your report includes:',
                includes: [
                    'Detailed grades by subject',
                    'Assignments and exams average',
                    'Updated cumulative grade',
                    'Approval status of each subject'
                ],
                motivationTitle: '💡 Remember:',
                motivation: 'Your effort and dedication are the key to success. Keep working consistently and you will see the results. We are here to support you!',
                contact: 'If you have any questions about your grades or need clarification, do not hesitate to contact us. We are here to help.',
                regards: 'Best regards,',
                legal: 'This is an automatic email generated by GradeApp. Please do not reply to this message.'
            },
            fr: {
                title: 'Rapport Académique',
                systemName: 'Système de Gestion Académique',
                greeting: 'Bonjour,',
                intro: 'Nous sommes heureux de partager avec vous votre <strong>rapport académique mis à jour</strong>. Vous trouverez ci-joint un document PDF avec le détail complet de vos notes.',
                includesTitle: '📊 Votre rapport comprend :',
                includes: [
                    'Notes détaillées par matière',
                    'Moyenne des devoirs et examens',
                    'Note cumulative mise à jour',
                    'État d\'approbation de chaque matière'
                ],
                motivationTitle: '💡 Rappelez-vous :',
                motivation: 'Vos efforts et votre dévouement sont la clé du succès. Continuez à travailler avec constance et vous verrez les résultats. Nous sommes là pour vous soutenir !',
                contact: 'Si vous avez des questions sur vos notes ou avez besoin d\'éclaircissements, n\'hésitez pas à nous contacter. Nous sommes là pour vous aider.',
                regards: 'Cordialement,',
                legal: 'Ceci est un e-mail automatique généré par GradeApp. Veuillez ne pas répondre à ce message.'
            },
            ht: {
                title: 'Rapò Akademik',
                systemName: 'Sistèm Jesyon Akademik',
                greeting: 'Bonjou,',
                intro: 'Nou kontan pataje avèk ou <strong>rapò akademik ou mete ajou</strong>. Tache nan imèl sa a w ap jwenn yon dokiman PDF ak detay konplè sou nòt ou yo.',
                includesTitle: '📊 Rapò ou gen ladan:',
                includes: [
                    'Nòt detaye pou chak matye',
                    'Mwayèn devwa ak egzamen',
                    'Nòt kimilatif ajou',
                    'Estati apwobasyon chak matye'
                ],
                motivationTitle: '💡 Sonje:',
                motivation: 'Efò ou ak devouman ou se kle siksè a. Kontinye travay nòmalman epi w ap wè rezilta yo. Nou la pou sipòte ou!',
                contact: 'Si ou gen nenpòt kesyon sou nòt ou yo oswa bezwen klarifikasyon, pa ezite kontakte nou. Nou la pou ede ou.',
                regards: 'Salitasyon,',
                legal: 'Sa a se yon imèl otomatik ki te pwodwi pa GradeApp. Tanpri pa reponn mesaj sa a.'
            }
        };

        const t = texts[lang] || texts.es;

        return `
<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${t.title} - ${student.name}</title>
</head>
<body style="margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; padding: 20px 0;">
        <tr>
            <td align="center">
                <!-- Container Principal -->
                <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
                    
                    <!-- Header -->
                    <tr>
                        <td style="background: linear-gradient(135deg, #3B82F6 0%, #2563EB 100%); padding: 40px 30px; text-align: center;">
                            <!-- Placeholder Logo Text if no image -->
                            <div style="width: 80px; height: 80px; margin: 0 auto 15px auto; background-color: rgba(255,255,255,0.2); border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-size: 32px; font-weight: bold;">
                                G
                            </div>
                            <!-- <img src="https://i.imgur.com/your-logo.png" alt="Logo" style="width: 80px; height: 80px; margin-bottom: 15px;"> -->
                            
                            <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 700;">GradeApp</h1>
                            <p style="color: #E0E7FF; margin: 5px 0 0 0; font-size: 14px;">${t.systemName}</p>
                        </td>
                    </tr>

                    <!-- Contenido Principal -->
                    <tr>
                        <td style="padding: 40px 30px;">
                            <!-- Saludo -->
                            <h2 style="color: #1E293B; margin: 0 0 10px 0; font-size: 24px; font-weight: 600;">
                                ${t.greeting} ${student.name}! 👋
                            </h2>
                            <p style="color: #64748B; margin: 0 0 25px 0; font-size: 14px;">
                                ${currentDate}
                            </p>

                            <!-- Mensaje Principal -->
                            <p style="color: #334155; margin: 0 0 20px 0; font-size: 16px; line-height: 1.6;">
                                ${t.intro}
                            </p>

                            <!-- Tarjeta de Información -->
                            <table width="100%" cellpadding="0" cellspacing="0" style="background: linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 100%); border-radius: 12px; padding: 20px; margin: 25px 0;">
                                <tr>
                                    <td>
                                        <h3 style="color: #0369A1; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;">
                                            ${t.includesTitle}
                                        </h3>
                                        <ul style="color: #0C4A6E; margin: 0; padding-left: 20px; line-height: 1.8;">
                                            ${t.includes.map(item => `<li>${item}</li>`).join('')}
                                        </ul>
                                    </td>
                                </tr>
                            </table>

                            <!-- Mensaje de Motivación -->
                            <table width="100%" cellpadding="0" cellspacing="0" style="background: linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 100%); border-left: 4px solid #22C55E; border-radius: 8px; padding: 15px 20px; margin: 20px 0;">
                                <tr>
                                    <td>
                                        <p style="color: #166534; margin: 0; font-size: 14px; line-height: 1.6;">
                                            <strong>${t.motivationTitle}</strong> ${t.motivation}
                                        </p>
                                    </td>
                                </tr>
                            </table>

                            <!-- Información de Contacto -->
                            <p style="color: #334155; margin: 25px 0 0 0; font-size: 14px; line-height: 1.6;">
                                ${t.contact}
                            </p>
                        </td>
                    </tr>

                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #F8FAFC; padding: 30px; text-align: center; border-top: 1px solid #E2E8F0;">
                            <p style="color: #64748B; margin: 0 0 10px 0; font-size: 14px; font-weight: 600;">
                                ${t.regards}
                            </p>
                            <p style="color: #3B82F6; margin: 0 0 15px 0; font-size: 16px; font-weight: 700;">
                                ${EmailService.config.fromName}
                            </p>
                            
                            <!-- Nota Legal -->
                            <p style="color: #94A3B8; margin: 20px 0 0 0; font-size: 11px; line-height: 1.5;">
                                ${t.legal}
                            </p>
                            
                            <p style="color: #CBD5E1; margin: 10px 0 0 0; font-size: 10px;">
                                © ${new Date().getFullYear()} GradeApp.
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
        `.trim();
    },

    // Enviar email con plantilla profesional
    sendEmail: async (to, subject, htmlBody, attachment = null) => {
        console.log('📧 Preparando envío de email...');
        console.log('Para:', to);
        console.log('Asunto:', subject);
        
        try {
            // Llamar a la API del backend
            const response = await fetch('http://localhost:3001/api/email/send', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    to,
                    from: EmailService.config.fromEmail,
                    fromName: EmailService.config.fromName,
                    replyTo: EmailService.config.replyTo,
                    subject,
                    html: htmlBody,
                    attachment: attachment ? {
                        name: attachment.name,
                        data: attachment.data,
                        type: 'application/pdf'
                    } : null
                })
            });

            const result = await response.json();
            
            if (result.success) {
                console.log('✅ Email enviado exitosamente');
                return result;
            } else {
                console.error('❌ Error al enviar email:', result.error);
                throw new Error(result.error || 'Error al enviar email');
            }
        } catch (error) {
            console.error('❌ Error al enviar email:', error);
            throw error;
        }
    },

    // Enviar reporte individual a estudiante
    sendStudentReport: async (student, pdfBlob, lang = 'es') => {
        const subject = `📊 ${lang === 'en' ? 'Your Academic Report' : lang === 'fr' ? 'Votre Rapport Académique' : lang === 'ht' ? 'Rapò Akademik ou' : 'Tu Reporte Académico'} - ${new Date().toLocaleDateString(lang === 'en' ? 'en-US' : lang === 'fr' ? 'fr-FR' : 'es-ES')}`;
        const htmlBody = EmailService.generateEmailTemplate(student, 'individual', lang);

        // Convertir PDF Blob a Base64
        const pdfBase64 = await new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => {
                const base64 = reader.result.split(',')[1];
                resolve(base64);
            };
            reader.readAsDataURL(pdfBlob);
        });

        return await EmailService.sendEmail(
            student.email,
            subject,
            htmlBody,
            {
                name: `Reporte_${student.name.replace(/\s+/g, '_')}_${Date.now()}.pdf`,
                data: pdfBase64
            }
        );
    },

    // Enviar reportes masivos
    sendBulkReports: async (reports, onProgress = null, lang = 'es') => {
        const results = [];
        const total = reports.length;

        for (let i = 0; i < reports.length; i++) {
            const report = reports[i];
            
            try {
                const result = await EmailService.sendStudentReport(report.student, report.pdfBlob, lang);
                results.push({
                    student: report.student.name,
                    email: report.student.email,
                    success: true,
                    ...result
                });

                // Callback de progreso
                if (onProgress) {
                    onProgress({
                        current: i + 1,
                        total,
                        student: report.student.name,
                        status: 'success'
                    });
                }
            } catch (error) {
                results.push({
                    student: report.student.name,
                    email: report.student.email,
                    success: false,
                    error: error.message
                });

                // Callback de progreso
                if (onProgress) {
                    onProgress({
                        current: i + 1,
                        total,
                        student: report.student.name,
                        status: 'error',
                        error: error.message
                    });
                }
            }

            // Pequeño delay entre envíos para no saturar
            if (i < reports.length - 1) {
                await new Promise(resolve => setTimeout(resolve, 500));
            }
        }

        return results;
    },

    // Configurar correo institucional localmente
    setInstitutionalEmail: (fromEmail, fromName, replyTo) => {
        EmailService.config.fromEmail = fromEmail;
        EmailService.config.fromName = fromName;
        EmailService.config.replyTo = replyTo;
        
        console.log('✅ Configuración de correo actualizada localmente:', EmailService.config);
    },
    
    // Guardar credenciales en el backend (Persistencia)
    saveConfiguration: async (email, password, name) => {
        try {
            const response = await fetch('http://localhost:3001/api/email/config', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    email,
                    password,
                    name
                })
            });
            const result = await response.json();
            
            if (result.success) {
                // Actualizar local
                EmailService.setInstitutionalEmail(email, name, email);
                return true;
            } else {
                throw new Error(result.error);
            }
        } catch (error) {
            console.error('Error saving email config:', error);
            throw error;
        }
    },

    // Obtener configuración actual
    getConfig: () => {
        return { ...EmailService.config };
    }
};

export default EmailService;
